FROM node:23-alpine3.19

WORKDIR /app

# Copy only the package files first (faster rebuilds)
COPY package*.json ./
RUN npm install

# Copy the rest of the project
COPY . .

# Expose the React dev server port
EXPOSE 3000

# Start the dev server with hot reload + watch
CMD ["npm", "start"]